### ISSUE TITLE
Solutes are pixelated and strokes vary in width during animation and pause

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/membrane-transport#193]
We're seeing some animation artefacts on the solutes (especially glucose and the symbols inside of Na and K). It's most notable on the thicker line on the bottom of glucose. The lines appear to change width depending on the direction the solute is moving and the screen size. Less noticeable if you use pan and zoom to zoom in.

AM suggested this may be improved if we draw the solutes in code instead. The SVG paths and colors are in the existing files. We don't have many examples that come to mind of animating SVGs quite this much.

@samreid , @jessegreenberg : what do you think? Is this an issue with the SVG that could be alleviated by drawing them in code?

**Comment by jessegreenberg** [comment]
I tried to see this in Win 11 Chrome and Edge but I can't see any artifacts for glucose, Na or K. @brettfiedler would you mind adding a screenshot of what you are seeing (if that is possible)?

The SVGs are being rasterized to an image before drawing to a canvas. It might be related to that part.

**Comment by jessegreenberg** [comment]
I can see this more easily on my 3840x2160 monitor when I make the browser window small.

**Comment by jessegreenberg** [comment]
I tried adjusting the `resolution` option but I don't notice any difference.

I think scaling down the Node before rasterizing it is helping, but it is difficult to see. I committed that, @brettfiedler can you see if that improves things?

If not, we can try smaller SVG artwork for the particles to test the theory from o3.

**Comment by brettfiedler** [comment]
Taking some random screenshots, I oculd be led to believe it's better, especially for the plus signs. I can still see the glucose bottom stroke change a bit. I'll need to check on my laptop, since that has a higher DPI.

![Image](https://github.com/user-attachments/assets/8d5afa1e-601e-4927-bc73-26d1dec3dd7b)

![Image](https://github.com/user-attachments/assets/675cce0e-e1e1-4db5-a2fe-087727beb036)

**Comment by jessegreenberg** [comment]
We had to revert this change because it introduced https://github.com/phetsims/membrane-transport/issues/325. We will need to explore other ways to get around this problem.

**Comment by jessegreenberg** [comment]
Brainstorming possibilities that we may or may not pursue:

Observe ize of images through the pipeline. What is the original size? What is the size after rasterize? What is the size right befor we draw?

We also talked about experimenting with the rasterize options. Some of those could be disrupting bounds.

We talked about testing with pngs instead of SVG.

We talked about experimenting with mipmaps.

**Comment by samreid** [comment]
Since we decided to go to RC 1 with no more work here, I recommend closing as will-not-fix. We can re-open it later if needed.
